version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo pip install tox

      - run:
          name: tox
          command: tox
